# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dajiuye?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: weiwenping

    druid:
      #      aop-pattern: com.example.*  #监控springboot
      #      driver-class-name: com.mysql.jdbc.Driver
      #      url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      #      username: root
      #      password: 123456
      filters: stat,wall,config  # log4j
      stat-view-servlet:         #配置监控页作用
        login-username: admin
        login-password: admin
        resetEnable: false
        url-pattern: /druid/*
        enabled: true
        allow: 0.0.0.0
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
pagehelper:
  helper-dialect: mysql  # 指定数据库类型
  reasonable: true # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时）
  params: count=sountSql # 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  support-methods-arguments: true
#  closeConn：true # 默认值为 true。当使用运行时动态数据源或没有设置 helperDialect 属性自动获取数据库类型时，会自动获取一个数据库连接， 通过该属性来设置是否关闭获取的这个连接，默认true关闭，设置为 false 后，不会关闭获取的连接，这个参数的设置要根据自己选择的数据源来决定。

# 七牛对象存储
oss:
  qiniu:
    domain: http://r1fbd6hev.hn-bkt.clouddn.com # 七牛测试域名
    accessKey: buvx6P_vmLvrridYHFGNkSQyJ9HpIxpWmZoj24yO # 公匙
    secretKey: iicDp_KVQqYX3oZMdZWgpQ_DdrY1i7_2ocgdC-gr # 私钥
    bucketName: dajiuye # 空间名

# aliyun oss
# 文件上传大小限制
#  spring.servlet.multipart.max-file-size=100MB
#  spring.servlet.multipart.max-request-size=1000MB
# 地域节点
aliyun.endPoint: oss-cn-shenzhen.aliyuncs.com
# Bucket 域名
aliyun.urlPrefix: https://dajiuye2.oss-cn-shenzhen.aliyuncs.com/
# accessKey Id
aliyun.accessKeyId: LTAI5tP7Kk3xA1M4oJawzdH7
# accessKey Secret
aliyun.accessKeySecret: rTlHPzyvVTfretbT4jPKRNaLgauMzu
# 你的Bucket名称
aliyun.bucketName: dajiuye2
# 目标文件夹
aliyun.fileHost: test

# 获取微信小程序的sessionKey
wx:
  url: api.weixin.qq.com/sns/jscode2session
  appid: wxffd8f31f5bb7f05f
  secret: cbd7c96d30b4fb835baae48dbf2c510c
  grant_type: authorization_code

# 发送微信http请求的
httppool:
  max_total: 200
  max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000

management:
  security:
    enabled: false